In [1]:
import numpy as np

Выбор данных

In [2]:
a = np.random.randint(0, 20, 10)
a

array([13, 11, 14, 12,  7, 17,  0, 11, 19,  2])

In [4]:
a[a > 10]  # выборка чисел согласно условию [a > 10]

array([13, 11, 14, 12, 17, 11, 19])

In [5]:
a[(a > 10) & (a % 2 == 0)]  # условие И

array([14, 12])

In [7]:
a[(a > 10) | (a % 3 == 0)]  # условие ИЛИ

array([13, 11, 14, 12, 17,  0, 11, 19])

**numpy.where** - первый вариант применения

In [9]:
a

array([13, 11, 14, 12,  7, 17,  0, 11, 19,  2])

In [10]:
np.where( a > 10)   # возвращает индексы чисел, согласно условию ( a > 10)

(array([0, 1, 2, 3, 5, 7, 8], dtype=int64),)

In [11]:
a[np.where(a > 10)]

array([13, 11, 14, 12, 17, 11, 19])

**numpy.where** - второй вариант применения

In [12]:
a = [1,4,7]
b = [9,2,5]

In [14]:
# Если в условии True, то берем элемент из массива a,
# если False - то из b
np.where([True, False, True], a, b)

array([1, 2, 7])

### Сотрировка

In [15]:
a = np.array([[1,3,9,9],
             [5,0,1,5],
             [2,7,3,5]])

In [16]:
a[[0,2,1], :] # сортируем по столбцу 0 в ручную

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [17]:
a.argsort(axis = 0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]], dtype=int64)

In [18]:
a[:, 0].argsort()

array([0, 2, 1], dtype=int64)

In [19]:
a[a[:, 0].argsort(), :]  # сортируем по столбцу 0 argsort

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

### Случайное перемешивание массивов

Одномерные массивы

In [20]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# inplace - на месте
np.random.shuffle(a)  # меняет массив на новый

In [22]:
a

array([5, 9, 8, 2, 6, 3, 0, 1, 7, 4])

Двумерные массивы перемешиваются только строки

In [23]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
# inplace
np.random.shuffle(a)

In [25]:
a

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Математические действия с массивами

Применение математических функций ко всему массиву

In [26]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# Логарифм по основанию e
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [28]:
# Экспонента
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [29]:
a.sum()

21

In [30]:
a.sum(axis = 0)  # суммируются значения по каждому столбцу

array([5, 7, 9])

In [31]:
a.sum(axis = 1)  # суммируются значения по каждой строке

array([ 6, 15])

In [33]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

## Поэлементное (не матричное) умножение

In [36]:
a = np.arange(12).reshape(3, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
b = np.arange(12, 24).reshape(-1, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

## Brodacasting

In [39]:
a = np.array([[2,5],
             [3,4],
             [6,1]])

1 случай - совпадает только число столбцов

In [40]:
b = np.array([1,2])

In [41]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

2 случай - совпадает только число строк

In [43]:
c = np.array([[1],
             [2],
             [3]])

In [44]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

### Статистические функции

In [45]:
a = np.random.randint(0,12,(3,4))
a

array([[ 5,  2, 11,  9],
       [11,  4,  0,  6],
       [ 6,  8,  9,  7]])

In [46]:
a.min()

0

In [47]:
a.min(axis = 0)

array([5, 2, 0, 6])

In [48]:
a.min(axis = 1)

array([2, 0, 6])

In [49]:
a.mean(axis = 0)  # среднее значение по столбцам

array([7.33333333, 4.66666667, 6.66666667, 7.33333333])

In [50]:
a.std(axis = 0)  # среднее квадратичное отклонение

array([2.62466929, 2.49443826, 4.78423336, 1.24721913])

### Запись и чтение массива из файла

In [51]:
np.save('a.npy', a)   # сохранение массива в файл

In [52]:
b = np.load('a.npy')

In [53]:
b

array([[ 5,  2, 11,  9],
       [11,  4,  0,  6],
       [ 6,  8,  9,  7]])

In [54]:
a

array([[ 5,  2, 11,  9],
       [11,  4,  0,  6],
       [ 6,  8,  9,  7]])